enabled: true
disable-rak: true
synapses:
# - enabled: true
#   server-ip: 127.0.0.1
#   server-port: 10305
#   is-main-server: true
#   server-password: 32bitlongkey
#   description: "A Synapse client"
loadingScreen: true